localStorage.setItem("adminAuthToken", JSON.stringify("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lODEwIiwiaWF0IjoxNjk3MzQ5OTAzLCJleHAiOjQ4NTA5NDk5MDN9.gj2KHG8cbsU6alm28tXeaPkiu-pKbdZr2a2PS2FEzAE"));
var packageIDs = [];
$(document).ready(() => {

    let auth = {
        "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
    }
    axios.get("http://localhost:8080/api/v1/packages/getAllIDs", {headers: auth})
        .then((res) => {
            packageIDs = res.data;

        })
        .catch(() => {
            swal("OOPS!", "Something went wrong while fetching PIDs!", "error")
        })


});

function changeTitle(title) {
    if (title === 'Home.') {
        return window.location.reload();

    }
    document.title = title;
}

$("#home").on("click", () => {
    window.location.reload();
})

$("#logout").on("click", () => {
    window.location.href = "adminLogin.html";
});
$("#guideManager").on("click", () => {


    $(".mainContent").css("display", "none");


    $("#vehicleTable").css("display", "none");


    $("body").append("<div id='forms' class='flexContainer  marginAdder'>" + "<div class=\"mb-3\">\n" + "  <label for=\"vehicleId\" class=\"form-label\">Vehicle ID.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"vehicleId\" placeholder=\"Generated by the server.\">\n" + "</div>\n" + "<div class=\"mb-3\">\n" + " <div class=\"mb-3\">\n" + "  <label for=\"packageId\" class=\"form-label\">Package ID.</label>\n" + "  <select class=\"form-select\" id=\"packageId\">\n" +

        "  </select>\n" + "</div>\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "  <label for=\"vehicleBrand\" class=\"form-label\">Vehicle Brand.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"vehicleBrand\" placeholder=\"Mitsubishi.\">\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "<div class=\"mb-3\">\n" + "  <label for=\"vehicleCategory\" class=\"form-label\">Vehicle Category.</label>\n" + "  <select class=\"form-select\" id=\"vehicleCategory\">\n" + "    <option value=\"Economy\">Economy</option>\n" + "    <option value=\"Mid Range\">Mid Range</option>\n" + "    <option value=\"Luxury\">Luxury</option>\n" + "    <option value=\"Super Luxury\">Super Luxury</option>\n" + "  </select>\n" + "</div>\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "  \n" + "\n" + "<div class=\"mb-3\">\n" + "  <label for=\"fuelType\" class=\"form-label\">Fuel Type.</label>\n" + "  <select class=\"form-select\" id=\"fuelType\">\n" + "    <option value=\"D/A\">D/A</option>\n" + "    <option value=\"D/M\">D/M</option>\n" + "    <option value=\"P/A\">P/A</option>\n" + "    <option value=\"P/M\">P/M</option>\n" + "\n" + "\n" + "\n" + "\n" + "  </select>\n" + "</div>\n" + "\n" + "\n" + "\n" + "\n" + "<div class=\"mb-3\">\n" + "  <label for=\"isHybrid\" class=\"form-label\">Is Hybrid?.</label>\n" + "  <select class=\"form-select\" id=\"isHybrid\">\n" + "    <option value=\"Yes\">Yes</option>\n" + "    <option value=\"No\">No</option>\n" + "\n" + "\n" + "\n" + "\n" + "\n" + "  </select>\n" + "</div>\n" + "\n" + "\n" + "</div>\n" + "<div class=\"mb-3\">\n"  +" <label for=\"fuelUsage\" class=\"form-label\">Fuel Usage.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"fuelUsage\" placeholder=\"\">\n"+"<label for=\"vehicleImageLocation\" class=\"form-label\">Vehicle Image Location.</label>"+ "  <input type=\"file\" class=\"form-control\" id=\"vehicleImageLocation\" placeholder=\"\">\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "  <label for=\"seatCapacity\" class=\"form-label\">Seat Capacity.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"seatCapacity\" placeholder=\"\">\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "  <label for=\"vehicleType\" class=\"form-label\">Vehicle Type.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"vehicleType\" placeholder=\"Type of Vehicle.\">\n" + "</div>\n" + "<div class=\"mb-3\">\n" + "  <label for=\"transmissionType\" class=\"form-label\">Transmission Type.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"transmissionType\" placeholder=\"Enter Transmission type.\">\n" + "<div class=\"mb-3\">\n" + "  <label for=\"driversContactNumber\" class=\"form-label\">Drivers Contact Number.</label>\n" + " <input type=\"text\" class=\"form-control\" id=\"driversLicenseImageLocation\" placeholder=\"\">\n"+"<label for=\"driversLicenseImageLocation\" class=\"form-label\">Drivers License Image Location.</label>"+ "  <input type=\"file\" class=\"form-control\" id=\"driversLicenseImageLocation\" placeholder=\"\">\n" + "</div>\n" +"<label for=\"remarks\" class=\"form-label\">Remarks.</label>\n" + "  <input type=\"text\" class=\"form-control\" id=\"remarks\" placeholder=\"Enter remarks here.\">\n"+


        "</div>\n" + "<button type=\"button\" id='saveVehicle' class=\"btn btn-success\">Save Vehicle.</button>\n" + "<button type=\"button\" id='updateVehicle' class=\"btn btn-primary\">Update Vehicle.</button>\n" + "" + "<button type=\"button\" id='deleteVehicle' class=\"btn btn-danger\">Delete Vehicle.</button>\n" + "<button type=\"button\" id='clearButton' class=\"btn btn-info\">Clear.</button>\n" +


        "</div>")

    setPackageIDs();
    $("#hotelId").prop("disabled", true);
});
var hCategory = '';
var isPetsAllowedOrNot = '';
var pId = '';
$(document).ready(() => {
    $(document).on("click", "#hotelCategory", () => {
        hCategory = $("#hotelCategory").val();

    })
    $(document).on("click", "#isPetsAllowed", () => {
        console.log($("#isPetsAllowed").val())
        hCategory = $("#isPetsAllowed").val();

    })
    $(document).on("click", "#packageId", () => {
        pId = $("#packageId").val();
        console.log($("#packageId").val())
        console.log("package id clicked" + $("#packageId").val())


    })
});
var hcl = '';
$(document).ready(() => {

    $(document).on("click", "#saveHotel", () => {
        if (!validator()) {
            return swal("Operation failed!", "Please fill all the fields!", "error")


        }

        saveImage();
        setTimeout(() => {
            let hotel = {
                hotelId: "",
                packageId: pId,
                hotelName: $("#hotelName").val(),
                hotelCategory: hCategory,
                hotelLocation: $("#hotelLocation").val(),
                hotelLocationWithCoordinates: $("#hotelLocationWithCoordinates").val(),
                hotelImageLocation: hcl,
                hotelContactEmail: $("#hotelEmail").val(),
                hotelContact1: $("#hotelContact1").val(),
                hotelContact2: $("#hotelContact2").val(),
                fullBoardWithACLuxuryRoomDouble: $("#fullBoardWithACLuxuryRoomDouble").val(),
                halfBoardWithACLuxuryRoomDouble: $("#halfBoardWithACLuxuryRoomDouble").val(),
                fullBoardWithACLuxuryRoomTriple: $("#fullBoardWithACLuxuryRoomTriple").val(),
                halfBoardWithACLuxuryRoomTriple: $("#halfBoardWithACLuxuryRoomTriple").val(),
                isPetsAllowed: isPetsAllowedOrNot,
                hotelFee: $("#hotelFee").val(),
                cancellationCriteria: $("#cancellationCriteria").val(),
                remarks: $("#remarks").val()

            }

            $.ajax({
                url: "http://localhost:8080/api/v1/hotels/save", method: "POST", headers: {
                    "content-type": "application/json",
                    "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
                }, data: JSON.stringify(hotel), success: (response) => {
                    if (response.statusCode === 200 || response.statusCode === 201) {
                        swal("Done!", response.message, "success")
                        return clearFields();

                    } else {
                        return swal("OOPS!", response.message, "error")

                    }


                }, error: (error) => {
                    swal("OOPS!", "An error occurred while communicating with the server ! ", "error");

                },


            })

        }, 5000)


    })

});

function saveImage() {
    var formData = new FormData();
    var file = $('#hotelImageLocation')[0].files[0];
    formData.append('imageFile', file);

    $.ajax({
        url: 'http://localhost:8090/upload', type: 'POST', data: formData, headers: {
            "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
        }, cache: false, contentType: false, processData: false, success: function (data) {

            hcl = data;
            console.log("IMG : " + hcl)


        }, error: function () {
            swal("OOPS!", "An error occurred while communicating with the server ! ", "error");
        }
    });

}

function clearFields() {
    $("#vehicleId").val("");
    $("#packageId").val("");
    $("#vehicleBrand").val("");
    $("#vehicleCategory").val("");
    $("#fuelType").val("");
    $("#isHybrid").val("");
    $("#fuelUsage").val("");
    $("#vehicleImageLocation").val("");
    $("#seatCapacity").val("");
    $("#vehicleType").val("");
    $("#transmissionType").val("");
    $("#driversContactNumber").val("");
    $("#driversLicenseImageLocation").val("");
    $("#remarks").val("");


}

function validator() {
    if ($("#packageId") || $("#vehicleBrand").val() === ""||$("#vehicleCategory").val() === ""||$("#fuelType").val() === ""||$("#isHybrid").val() === ""||$("#fuelUsage").val() === ""||$("#vehicleImageLocation").val() === ""||$("#seatCapacity").val() === ""||$("#vehicleType").val() === ""||$("#transmissionType").val() === ""||$("#driversContactNumber").val() === ""||$("#driversLicenseImageLocation").val() === ""||$("#remarks").val() === "") {
        return false;
    }
    return true;


}

$(document).ready(() => {


    $(document).on("click", "#clearButton", () => {
        clearFields();
    })
})
$(document).ready(() => {
    $(document).on("click", "#updateHotel", () => {
        if (!validator()) {
            return swal("Operation failed!", "Please fill all the fields!", "error")

        }
        saveImage();
        setTimeout(() => {
            let hotel = {
                hotelId: $("#hotelId").val(),
                packageId: pId,
                hotelName: $("#hotelName").val(),
                hotelCategory: hCategory,
                hotelLocation: $("#hotelLocation").val(),
                hotelLocationWithCoordinates: $("#hotelLocationWithCoordinates").val(),
                hotelImageLocation: hcl,
                hotelContactEmail: $("#hotelEmail").val(),
                hotelContact1: $("#hotelContact1").val(),
                hotelContact2: $("#hotelContact2").val(),
                fullBoardWithACLuxuryRoomDouble: $("#fullBoardWithACLuxuryRoomDouble").val(),
                halfBoardWithACLuxuryRoomDouble: $("#halfBoardWithACLuxuryRoomDouble").val(),
                fullBoardWithACLuxuryRoomTriple: $("#fullBoardWithACLuxuryRoomTriple").val(),
                halfBoardWithACLuxuryRoomTriple: $("#halfBoardWithACLuxuryRoomTriple").val(),
                isPetsAllowed: isPetsAllowedOrNot,
                hotelFee: $("#hotelFee").val(),
                cancellationCriteria: $("#cancellationCriteria").val(),
                remarks: $("#remarks").val()

            }
            console.log(hotel)
            $.ajax({
                url: "http://localhost:8080/api/v1/hotels/update", method: "PUT", headers: {
                    "content-type": "application/json",
                    "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
                }, data: JSON.stringify(hotel), success: (response) => {
                    if (response.statusCode === 200 || response.statusCode === 201) {
                        swal("Done!", response.message, "success")
                        return clearFields();

                    } else {
                        return swal("OOPS!", response.message, "error")

                    }


                }, error: (error) => {
                    swal("OOPS!", "An error occurred while communicating with the server ! ", "error");

                },


            })

        }, 3000)

    })
})
$(document).ready(() => {
    $(document).on("keydown", "#hotelName", (event) => {

        if (event.key === 'Enter') {
            $.ajax({
                url: "http://localhost:8080/api/v1/hotels/getHotelByName?hotelName=" + $("#hotelName").val(),
                method: "GET",
                headers: {
                    "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
                },
                success: (res) => {
                    console.log(res.data)
                    if (res.statusCode === 200 || res.statusCode === 201) {
                        $("#hotelId").prop("disabled", false);
                        $("#hotelId").val(res.data.hotelId);
                        $("#hotelId").prop("disabled", true);
                        console.log("real pid" + res.data.packageId)
                        $("#packageId").val(res.data.packageId);
                        $("#hotelName").val(res.data.hotelName);
                        $("#hotelCategory").append("<option value='" + res.data.hotelCategory + "'>" + res.data.hotelCategory + "</option>");
                        $("#hotelLocation").val(res.data.hotelLocation);
                        $("#hotelLocationWithCoordinates").val(res.data.hotelLocationWithCoordinates);
                        $("#hotelEmail").val(res.data.hotelContactEmail);
                        $("#hotelContact1").val(res.data.hotelContact1);
                        $("#hotelContact2").val(res.data.hotelContact2);
                        $("#fullBoardWithACLuxuryRoomDouble").val(res.data.fullBoardWithACLuxuryRoomDouble);
                        $("#halfBoardWithACLuxuryRoomDouble").val(res.data.halfBoardWithACLuxuryRoomDouble);
                        $("#fullBoardWithACLuxuryRoomTriple").val(res.data.fullBoardWithACLuxuryRoomTriple);
                        $("#halfBoardWithACLuxuryRoomTriple").val(res.data.halfBoardWithACLuxuryRoomTriple);
                        $("#isPetsAllowed").val(res.data.petsAllowed);
                        $("#hotelFee").val(res.data.hotelFee);
                        $("#cancellationCriteria").val(res.data.cancellationCriteria);
                        $("#remarks").val(res.data.remarks);


                        return swal("Done!", res.message, "success");

                    }
                    swal("OOPS!", res.message, "error");

                },
                error: (error) => {
                    swal("OOPS!", "An error occurred while communicating with the server ! ", "error");
                }


            });

        }


    })


});
$(document).ready(() => {
    $(document).on("click", "#deleteHotel", () => {
        if ($("#hotelId").val() === "") {
            return swal("OOPS!", "Please enter a Hotel name to delete!", "error");
        }

        $.ajax({
            url: "http://localhost:8080/api/v1/hotels/delete?hotelID=" + $("#hotelId").val(),
            method: "DELETE",
            headers: {
                "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
            },
            success: (res) => {
                console.log(res.data)
                if (res.statusCode === 200 || res.statusCode === 201) {

                    return swal("Done!", res.message, "success");

                }
                swal("OOPS!", res.message, "error");

            },
            error: (error) => {
                swal("OOPS!", "An error occurred while communicating with the server ! ", "error");
            }


        });


    })


});

$("#tableView").on("click", () => {

    $("#forms").css("display", "none");


    $(".mainContent").css("display", "none");


    $("body").append("<table data-aos='zoom-in' id='vehicleTable' class=\"table table-dark\">\n" +
        "  <thead>\n" +
        "    <tr>\n" +
        "      <th scope=\"col\">Vehicle ID</th>\n" +
        "      <th scope=\"col\">Package ID</th>\n" +
        "      <th scope=\"col\">Vehicle Brand</th>\n" +
        "      <th scope=\"col\">Vehicle Category</th>\n" +
        "      <th scope=\"col\">Fuel Type</th>\n" +
        "      <th scope=\"col\">Is Hybrid</th>\n" +
        "      <th scope=\"col\">Fuel Usage</th>\n" +
        "      <th scope=\"col\">Vehicle Image Location</th>\n" +
        "      <th scope=\"col\">Seat Capacity</th>\n" +
        "      <th scope=\"col\">Vehicle Type</th>\n" +
        "      <th scope=\"col\">Transmission Type</th>\n" +
        "      <th scope=\"col\">Drivers Contact Number</th>\n" +
        "      <th scope=\"col\">Drivers License Image Location</th>\n" +
        "      <th scope=\"col\">Remarks</th>\n" +
        "    </tr>\n" +
        "  </thead>\n" +
        "  <tbody></tbody>" +
        "</table>");



    $.ajax({
        url: "http://localhost:8080/api/v1/hotels/getAll", method: "GET", headers: {
            "Authorization": "Bearer " + JSON.parse(localStorage.getItem("adminAuthToken"))
        }, success: (res) => {


            res.data.map((hotel) => {


                let row = "<tr>\n" + "      <th scope=\"row\">" + hotel.hotelId + "</th>\n" + "      <td>" + hotel.packageId + "</td>\n" + "      <td>" + hotel.hotelCategory + "</td>\n" + "      <td>" + hotel.hotelLocation + "</td>\n" + "      <td>" + hotel.hotelLocationWithCoordinates + "</td>\n" + "      <td>" + hotel.hotelImageLocation + "</td>\n" + "      <td>" + hotel.hotelContactEmail + "</td>\n" + "      <td>" + hotel.hotelContact1 + "</td>\n" + "      <td>" + hotel.hotelContact2 + "</td>\n" + "      <td>" + hotel.fullBoardWithACLuxuryRoomDouble + "</td>\n" + "      <td>" + hotel.halfBoardWithACLuxuryRoomDouble + "</td>\n" + "      <td>" + hotel.fullBoardWithACLuxuryRoomTriple + "</td>\n" + "      <td>" + hotel.halfBoardWithACLuxuryRoomTriple + "</td>\n" + "      <td>" + hotel.petsAllowed + "</td>\n" + "      <td>" + hotel.hotelFee + "</td>\n" + "      <td>" + hotel.remarks + "</td>\n" + "    </tr>";
                $("#hotelTable tbody").append(row);

            })


        }, error: (error) => {
            swal("OOPS!", "An error occurred while communicating with the server ! ", "error");

        }


    })


});

function setPackageIDs() {
    packageIDs.forEach((pID) => {
        $("#packageId").append("<option value='" + pID + "'>" + pID + "</option>")
    })

}